### PR TITLE
Add dots two_fer, see exercism/elixir#877

### PR DESCRIPTION
**Pull request by mpas97**

### CODE REVIEW

**Comment by jiegillet** [comment]
Thank you, that's a lot of dots!

I ran `grep "one for me\"" **/*.ex*` and found 2 more.

https://github.com/exercism/elixir-analyzer/blob/e8706ab820c0e0373d208926d085c2797bc5a02e/lib/elixir_analyzer/test_suite/two_fer.ex#L133

https://github.com/exercism/elixir-analyzer/blob/e8706ab820c0e0373d208926d085c2797bc5a02e/test/support/exercise_test_case.ex#L37

**Comment by mpas97** [comment]
Thanks again! I was totally overwhelmed by all those test files for the same exercise... Enough dots now? :P

**Review by jiegillet — APPROVED** [review]
I think that's all the dots I can see! Thank you, Pacman 😉 

image

**Comment by jiegillet** [comment]
Oh, BTW, be careful about sending a PR from your `main` branch, that branch should be used to keep track of the repo's `main` branch.

@angelikatyborska please merge :)

**Review by angelikatyborska — APPROVED** [review]

**Comment by mpas97** [comment]
@jiegillet パックマン、すばらしいですね 。

To the branch problem: You are so right! I didn't even notice. I probably should have cloned everything and worked locally, but I just used the web IDE as I didn't expect so many changes to be done here. Anyway, lucky me that branches are not immutable :)

@angelikatyborska Thanks for the merge!

**Pull request merged**
