### PR TITLE
Mini refactoring

### PR DESCRIPTION
**Pull request by angelikatyborska**
I wanted to explore how to extend the functionality of the analyzer and found some opportunities for refactoring (IMO).

- Introduce a `Comment` struct that serves as documentation 
- Change `suppress_if` to a two tuple, mostly because you can't document a type like `[String.t(), :fail | :pass]`
- Rename some files and tests to remove any references to the old "status" and "referring to mentors"

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Something unexpected must have happened, a test is failing even though I shouldn't have changed anything that affects it 🙈

**Comment by neenjaw** [comment]
`Error: 07-09T03:57:58.176Z [] [error] Loading exercise test suite '' failed (nofile).` I've never seen this error before, have you?

**Comment by angelikatyborska** [comment]
Yes, that error is from the test case for `./test_data/two_fer/error_solution/` and it's expected. I added a `capture_log` call to avoid seeing this in the test output.

**Comment by angelikatyborska** [comment]
I reverted the commit that caused the weird test failure and did all the same changes again, split in more commits. All tests pass :) I must have made a mistake when renaming directories.

**Review by neenjaw — APPROVED** [review]
Nice refactor adding the struct constraint to the map

**Pull request merged**
