### PR TITLE
[#92] Write analysis for concept exercise `rpn-calculator-inspection`

### LINKED ISSUE #92: Write analysis for concept exercise `rpn-calculator-inspection`
Desired checks: https://github.com/exercism/elixir/blob/3cab99a5ce0649230d1f5aae563655b622ea737b/exercises/concept/rpn-calculator-inspection/.meta/design.md#L22-L24

### PR DESCRIPTION
**Pull request by jiegillet**
Closes #92

A simpler one.

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Perfect!

Btw. I think if you write "Closes [issue link]" or "fixes [issue link]" then GitHub will automatically close the issue when the PR gets merged. With "solves" it doesn't work 🙁

**Review by angelikatyborska — APPROVED** [review]

**Comment by angelikatyborska** [comment]
(I edited the comment to "closes" to see if it would work, it worked)

**Comment by jiegillet** [comment]
Oh man... I feel like an idiot, I've been typing "solves" for like 20 PRs lol.
Thank you :)

**Comment by angelikatyborska** [comment]
It's not that easy to find official documentation on this. The best I found is https://guides.github.com/features/issues/

> By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue.

**Pull request merged**
