### PR TITLE
Improve snake_case automatic recommendation for underscore followed by capital letter

### LINKED ISSUE #334: Elixir track snake_case misleading automatic recomendation
When the elixir track on the exercise log level when submitted I have got what I think is a wrong automatic recommendation about snake_case. The details of the recommendations are:

image

### PR DESCRIPTION
**Pull request by dmarcoux**
Fixes #334

### CODE REVIEW

**Comment by dmarcoux** [comment]
I'm trying to run the tests locally with `mix test --exclude external` and I get this error:

```
Excluding tags: [:external, :pending]


== Compilation error in file test/elixir_analyzer/exercise_test/assert_call/indirect_call_test.exs ==
** (CompileError) test/elixir_analyzer/exercise_test/assert_call/indirect_call_test.exs:2: module ElixirAnalyzer.ExerciseTestCase is not loaded and could not be found
    (elixir 1.14.0) expanding macro: Kernel.use/2
    test/elixir_analyzer/exercise_test/assert_call/indirect_call_test.exs:2: ElixirAnalyzer.ExerciseTest.AssertCall.IndirectCallTest (module)
```

What I did is I setup the repository with  `git submodule update --init --recursive`.

**Review by jiegillet — APPROVED** [review]
Perfect, thanks a lot!

**Comment by dmarcoux** [comment]
@jiegillet Do you know what could cause the error I'm having when trying to run the tests locally?

**Comment by jiegillet** [comment]
Mmh, I'm afraid I don't.
Did you manage to compile the project using `bin/build.sh`?
In any case it usually helps to start fresh, removing `_build`, that sort of things...

**Comment by dmarcoux** [comment]
I could compile the project with `bin/build.sh` and I also started fresh by removing `_build`, but I still get the error somehow. Is there an official way to setup this project? Is it with `asdf`? Or with Docker?

**Comment by jiegillet** [comment]
Not really, any of these should work. I use asdf, but I have pretty much the same versions of elixir as you
```
➜  elixir-analyzer git:(main) elixir --version
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

I'm sorry, I don't really know what else you can try...

**Comment by dmarcoux** [comment]
No worries, thank you for taking a look, it's appreciated!

**Pull request merged**
