### PR TITLE
Extend local calls to match when referencing the current module by name or __MODULE__

### PR DESCRIPTION
**Pull request by angelikatyborska**
Resolves https://github.com/exercism/elixir-analyzer/issues/267

### CODE REVIEW

**Comment by angelikatyborska** [comment]
I noticed a weird thing, rather unrelated to this PR: Whenever I run `mix test`, the file `test_data/lasagna/perfect_solution/expected_analysis.json` gets deleted 🤔

**Review by jiegillet — APPROVED** [review]
Awesome! 
This module is getting a bit complex, isn't it? I'm glad it's still possible to understand what's going on and improve it :)

**Comment by jiegillet** [comment]
> I noticed a weird thing, rather unrelated to this PR: Whenever I run `mix test`, the file `test_data/lasagna/perfect_solution/expected_analysis.json` gets deleted 🤔

Yeah, this happens to me too, I'm quite puzzled. I'll open an issue if I can't figure it out quickly.

**Comment by angelikatyborska** [comment]
It was quite challenging, yes, but the comments were a big help in figuring out what's what.

**Pull request merged**
