### PR TITLE
Add GitHub Action for Elixir CI

### PR DESCRIPTION
**Pull request by filalex77**
For now, this will just confirm it builds.

As soon as the test suite expands, it will be picked up here.

### CODE REVIEW

**Comment by neenjaw** [comment]
in PR #4 I am implementing a basic test unit, cleaning up some of the old ways I was testing the prototype.  If you rollback commit `Remove default 'Hello World' test` 788d9db we should be able to merge them both without conflict.

**Comment by neenjaw** [comment]
I'm not familiar enough with GHA to know if this is what we need, but it seems ok to me. @NobbZ I think has more experience, I have tagged him for review.

**Comment by filalex77** [comment]
@NobbZ It fails because there is no corresponding function in source. Either the function should be added, or the test should stay removed

**Comment by NobbZ** [comment]
I haven't actually looked into the test itself, I assumed its the regular `assert true`…

**Comment by filalex77** [comment]
@neenjaw I think this is safe to merge now.

**Comment by filalex77** [comment]
Great, it worked with tests from #8 :tada:
I'd be glad to improve this workflow if anyone has anything to suggest.

**Comment by neenjaw** [comment]
Eventually I think we need to do what the go/JavaScript team is doing with comments. I think they have a build check that any comment in the analyzer must have the matching markup in the [exercise/website-copy](https://github.com/exercism/website-copy/tree/master/automated-comments) repo

**Pull request merged**
